// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhjuzAHg-woBaatITckZX1lODXKtfNhdc',
    appId: '1:1094231347720:web:d6f1334aaae34c365637bd',
    messagingSenderId: '1094231347720',
    projectId: 'medicationapp-c4830',
    authDomain: 'medicationapp-c4830.firebaseapp.com',
    storageBucket: 'medicationapp-c4830.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdV3Np4UC62SqKRJxWcJLndvxa4ZEqq6k',
    appId: '1:1094231347720:android:af55f252589e81085637bd',
    messagingSenderId: '1094231347720',
    projectId: 'medicationapp-c4830',
    storageBucket: 'medicationapp-c4830.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk5gwnI0iX2Gt-p2nsiY5B9xKG_YaPLqs',
    appId: '1:1094231347720:ios:c967721a7a7118d95637bd',
    messagingSenderId: '1094231347720',
    projectId: 'medicationapp-c4830',
    storageBucket: 'medicationapp-c4830.appspot.com',
    iosBundleId: 'com.example.meditationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk5gwnI0iX2Gt-p2nsiY5B9xKG_YaPLqs',
    appId: '1:1094231347720:ios:b00315fe43afeff75637bd',
    messagingSenderId: '1094231347720',
    projectId: 'medicationapp-c4830',
    storageBucket: 'medicationapp-c4830.appspot.com',
    iosBundleId: 'com.example.meditationApp.RunnerTests',
  );
}
